### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by Karyum** [WebAhead8/Weather_cities_info#5]
To be honest I'm not sure what to code review since I helped in the code a lot 😄 

but the project turned out pretty good, simple and nicely written ([I would only change these variables to camelCase :stuck_out_tongue_winking_eye: ](https://github.com/WebAhead8/Weather_cities_info/blob/main/weather.js#L5-L6))

Goodjob

**Comment by MahmoudDiab25** [comment]
first of all thank you for the help and we will change them to camelCase
