### ISSUE TITLE
styling in Javascript

### ISSUE THREAD

**Issue by Karyum** [WebAhead8/Weather_cities_info#6]
this is a small issue, but instead of doing this https://github.com/WebAhead8/Weather_cities_info/blob/main/flags.js#L16-L17 , put the height and width in a class and give that class to the image.

styling in Javascript should only be allowed if the thing you are trying to achieve **cannot be done in CSS only**

**Comment by MahmoudDiab25** [comment]
ok but you have another img file which is icon for the wither from weather.js file so if i write class with img it will change the icon as well

**Comment by Karyum** [comment]
no it shouldn't unless you decide that it should, I'm saying create a class

```css

.myclass {

}
```

And not 

```css

img {

}

```

**Comment by MahmoudDiab25** [comment]
ok hhhh i with create one

**Comment by MahmoudDiab25** [comment]
we did it
