### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hadi1616** [WebAhead8/Weather_cities_info#7]
*)Nice Project, Well done you made a great job.
But We Faced little problems in:
1) understanding the main idea of the website - the project is not clear  in what it's  doing.
2) when we type israel , Maxico will appear and We think you should give us a letter saying that (Israel is not a city , or something like country not found ).

**Comment by KhaledBadarna** [comment]
1-try to read the read.me file again
2-the website is beta version, we will try to resolve the problem
